replicaCount: 1

image:
  repository: ghcr.io/andrewsdeon/ts-awesome-api-app
  tag: dev-ts-api-73630
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: dev-ts-awesome-api.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

env:
  APP_NAME: "dev-awesome-api"
  APP_ENV: "develop"
  APP_VERSION: "0.1.0"

secretEnv:
  SECRET_KEY:
    secretName: ts-awesome-api-dev-secret
