replicaCount: 1
image:
  repository: ghcr.io/andrewsdeon/ts-awesome-api-app
  tag: dev-ts-api-a6bf81c
  pullPolicy: IfNotPresent
  pullSecrets:
    - ghcr-secret
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: true
  className: nginx
  hosts:
    - host: dev-ts-awesome-api.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
env:
  APP_NAME: "dev-ts-awesome-api"
  APP_ENV: "development"
  APP_VERSION: "0.1.0"
secretEnv:
  SECRET_KEY:
    secretName: ts-awesome-api-dev-secret
configMap:
  name: dev-ts-api-ts-awesome-api-config
