replicaCount: 2

image:
  repository: myregistry/ts-awesome-api
  tag: "1.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: prod-ts-awesome-api.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

env:
  APP_NAME: "prod-ts-awesome-api"
  APP_ENV: "production"
  APP_VERSION: "0.1.0"

secretEnv:
  SECRET_KEY:
    secretName: ts-awesome-api-prod-secret
