apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ts-awesome-api.fullname" . }}-config
data:
  APP_NAME: {{ .Values.env.APP_NAME | quote }}
  APP_ENV: {{ .Values.env.APP_ENV | quote }}
  APP_VERSION: {{ .Values.env.APP_VERSION | quote }}
